Repository hubreviewapp/hubreview, pull requests merged in 2024-02, with the labels that each got.

#57 Get commits GitHub
  api-server/Core/Entities/ContributorInfo.cs
  api-server/Web/Controllers/GitHubController.cs
  web-client/src/components/NavBar.tsx
  web-client/src/components/PRCreate/CommitHistory.tsx
  web-client/src/components/PRDetailSideBar.tsx
  web-client/src/components/ReviewQueue/PRCard.tsx
  web-client/src/components/ReviewQueue/PRCardList.tsx
  web-client/src/models/PRInfo.tsx
  web-client/src/pages/PRDetailsPage.tsx
Labels: enhancement, refactoring

#62 Commit history & Label Add/Delete
  api-server/Core/Entities/CommitInfo.cs
  api-server/Web/Controllers/GitHubController.cs
  web-client/src/components/LabelButton.tsx
  web-client/src/components/PRCreate/CommitHistory.tsx
  web-client/src/components/PRDetailSideBar.tsx
  web-client/src/components/SelectLabel.tsx
  web-client/src/tabs/CommentsTab.tsx
Labels: documentation

#61 feat: submit a review comment
  api-server/Core/Entities/AssigneeInfo.cs
  api-server/Core/Entities/CollaboratorInfo.cs
  api-server/Web/Controllers/GitHubController.cs
  api-server/Web/Web.csproj
Labels: enhancement, question, refactoring

#76 Priority add delete GitHub
  web-client/src/components/PRCreate/PRSummaryBox.tsx
  web-client/src/components/PRDetailSideBar.tsx
  web-client/src/components/PriorityBadge.tsx
  web-client/src/components/SelectLabel.tsx
  web-client/src/pages/PRDetailsPage.tsx
  web-client/src/tabs/CommentsTab.tsx
Labels: Priority: High
